In [12]:
# --- 1. SETTINGS ---
# Your GitHub info (The "Key" to open the door)
GIT_TOKEN = userdata.get('GH_token')
GIT_USERNAME = "nguyenthihaiyenworking"
GIT_EMAIL = "nguyenthihaiyenworking@gmail.com"

# The Repository info (The "Destination")
REPO_OWNER = "nhnminh1409"
GIT_REPO = "instacart-market-basket-analysis"
SOURCE_PATH = "/content/drive/MyDrive/Instacart_Project/01_data_cleaning.ipynb"

print("✅ Configuration complete!")

✅ Configuration complete!

Step 1: Data loading with downcasting for memory optimization

In [19]:
import numpy as np
import pandas as pd

def reduce_mem_usage(df):
    start_mem = df.memory_usage().sum() / 1024**2

    for col in df.columns:
        col_type = df[col].dtype

        # Chỉ xử lý nếu là kiểu số (integer hoặc float)
        if pd.api.types.is_numeric_dtype(col_type):
            c_min = df[col].min()
            c_max = df[col].max()

            if pd.api.types.is_integer_dtype(col_type):
                if c_min > np.iinfo(np.int8).min and c_max < np.iinfo(np.int8).max:
                    df[col] = df[col].astype(np.int8)
                elif c_min > np.iinfo(np.int16).min and c_max < np.iinfo(np.int16).max:
                    df[col] = df[col].astype(np.int16)
                elif c_min > np.iinfo(np.int32).min and c_max < np.iinfo(np.int32).max:
                    df[col] = df[col].astype(np.int32)
                else:
                    df[col] = df[col].astype(np.int64)
            else:
                if c_min > np.finfo(np.float32).min and c_max < np.finfo(np.float32).max:
                    df[col] = df[col].astype(np.float32)
                else:
                    df[col] = df[col].astype(np.float64)

        # Nếu là kiểu object (chuỗi), chuyển sang category để tiết kiệm RAM
        elif col_type == object:
            df[col] = df[col].astype('category')

    end_mem = df.memory_usage().sum() / 1024**2
    print(f'Memory usage decreased to {end_mem:.2f} MB ({((start_mem - end_mem) / start_mem * 100):.1f}% reduction)')
    return df

In [14]:
import os

# 1. Define the directory path on your Google Drive
path = '/content/drive/MyDrive/Instacart_Project/'

# List of files to be processed
files = [
    'aisles.csv', 'departments.csv', 'products.csv',
    'orders.csv', 'order_products__prior.csv', 'order_products__train.csv'
]

data = {}

for file in files:
    # Combine the directory path with the filename
    full_path = os.path.join(path, file)

    if os.path.exists(full_path):
        print(f"Processing: {file}")

        # Read the CSV file
        df = pd.read_csv(full_path)

        # Apply downcasting (Make sure you have run the 'reduce_mem_usage' function cell first)
        df = reduce_mem_usage(df)

        # Store in the dictionary
        name = file.replace('.csv', '')
        data[name] = df
        print(f"Done with {name}!\n" + "-"*30)
    else:
        print(f"Warning: File {file} not found at {full_path}")

# Accessing the DataFrames:
orders = data['orders']
products = data['products']

Processing: aisles.csv
Memory usage decreased to 0.01 MB (-159.6% reduction)
Done with aisles!
------------------------------
Processing: departments.csv
Memory usage decreased to 0.00 MB (-91.9% reduction)
Done with departments!
------------------------------
Processing: products.csv
Memory usage decreased to 1.91 MB (-25.8% reduction)
Done with products!
------------------------------
Processing: orders.csv
Memory usage decreased to 52.20 MB (71.4% reduction)
Done with orders!
------------------------------
Processing: order_products__prior.csv
Memory usage decreased to 340.25 MB (65.6% reduction)
Done with order_products__prior!
------------------------------
Processing: order_products__train.csv
Memory usage decreased to 13.20 MB (68.7% reduction)
Done with order_products__train!
------------------------------

In [15]:
# Handle the days_since_prior_order column immediately after loading
data['orders']['days_since_prior_order'] = data['orders']['days_since_prior_order'].fillna(0)
print("Finished handling NaN values for the first orders.")

Finished handling NaN values for the first orders.

Step 2: Merging data tables (orders, products, aisles, depts)

In [28]:
# 1. Merge products with aisles
# Logic: Use the products table as the base and perform a left join with the aisles table
# using 'aisle_id' to retrieve the aisle names.
products_full = data['products'].merge(data['aisles'], on='aisle_id', how='left')

# 2. Merge with departments
# Join the previous result with the departments table using 'department_id'
products_full = products_full.merge(data['departments'], on='department_id', how='left')

# Immediately optimize RAM for the newly created table
products_full = reduce_mem_usage(products_full)

print("Table 'products_full' complete. Current structure:")
print(products_full.columns.tolist())
# Result includes: product_id, product_name, aisle_id, department_id, aisle, department

Memory usage decreased to 2.06 MB (0.0% reduction)
Table 'products_full' complete. Current structure:
['product_id', 'product_name', 'aisle_id', 'department_id', 'aisle', 'department']

In [29]:
# Join order details (prior) with full product information (products_full)
prior_details = data['order_products__prior'].merge(products_full, on='product_id', how='left')

# Optimize RAM usage (Crucial as this table contains tens of millions of rows)
prior_details = reduce_mem_usage(prior_details)

print("Product information successfully merged into the 'prior' order details.")

Memory usage decreased to 650.96 MB (0.0% reduction)
Product information successfully merged into the 'prior' order details.

In [30]:
# Join the prior_details table with the orders table
# Note: This 'orders' table already has missing values handled (fillna(0)) from the previous step
prior_final = prior_details.merge(data['orders'], on='order_id', how='left')

# Final RAM optimization
prior_final = reduce_mem_usage(prior_final)

print("PRIOR master table complete!")
display(prior_final.head())

Memory usage decreased to 1022.15 MB (0.0% reduction)
PRIOR master table complete!

,order_id,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,aisle,department,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2,33120,1,1,Organic Egg Whites,86,16,eggs,dairy eggs,202279,prior,3,5,9,8.0
1,2,28985,2,1,Michigan Organic Kale,83,4,fresh vegetables,produce,202279,prior,3,5,9,8.0
2,2,9327,3,0,Garlic Powder,104,13,spices seasonings,pantry,202279,prior,3,5,9,8.0
3,2,45918,4,1,Coconut Butter,19,13,oils vinegars,pantry,202279,prior,3,5,9,8.0
4,2,30035,5,0,Natural Sweetener,17,13,baking ingredients,pantry,202279,prior,3,5,9,8.0

In [31]:
# Merge train set with products_full
train_details = data['order_products__train'].merge(products_full, on='product_id', how='left')

# Further merge with orders
train_final = train_details.merge(data['orders'], on='order_id', how='left')

# Optimize RAM usage
train_final = reduce_mem_usage(train_final)

print("TRAIN master table complete!")

Memory usage decreased to 43.65 MB (0.0% reduction)
TRAIN master table complete!

In [32]:
# Desired column order (Feel free to customize this as needed)
cols_order = [
    'order_id', 'user_id', 'eval_set', 'order_number', 'order_dow', 'order_hour_of_day', 'days_since_prior_order', # Order Information Group
    'product_id', 'product_name',                                                                              # Product Information Group
    'aisle_id', 'aisle',                                                                                       # Aisle Information Group
    'department_id', 'department',                                                                             # Department Information Group
    'add_to_cart_order', 'reordered'                                                                           # Transaction/Behavior Group
]

# Apply the new column order to the prior_final table
# Note: Using a list comprehension to select only existing columns to prevent errors
prior_final = prior_final[[c for c in cols_order if c in prior_final.columns]]

# Apply the same logic to train_final
train_final = train_final[[c for c in cols_order if c in train_final.columns]]

print("Columns successfully reorganized!")
display(prior_final.head())

Columns successfully reorganized!

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,product_name,aisle_id,aisle,department_id,department,add_to_cart_order,reordered
0,2,202279,prior,3,5,9,8.0,33120,Organic Egg Whites,86,eggs,16,dairy eggs,1,1
1,2,202279,prior,3,5,9,8.0,28985,Michigan Organic Kale,83,fresh vegetables,4,produce,2,1
2,2,202279,prior,3,5,9,8.0,9327,Garlic Powder,104,spices seasonings,13,pantry,3,0
3,2,202279,prior,3,5,9,8.0,45918,Coconut Butter,19,oils vinegars,13,pantry,4,1
4,2,202279,prior,3,5,9,8.0,30035,Natural Sweetener,17,baking ingredients,13,pantry,5,0

In [33]:
# 1. Review the first 5 rows to verify column alignment
print("--- First 5 rows of prior_final ---")
display(prior_final.head())

# 2. Check column list and data types (Confirming user_id, order_hour_of_day, etc.)
print("\n--- Table Schema Information ---")
prior_final.info()

# 3. Check dimensions (Total rows and columns)
print(f"\nTable Dimensions: {prior_final.shape}")

--- First 5 rows of prior_final ---

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,product_name,aisle_id,aisle,department_id,department,add_to_cart_order,reordered
0,2,202279,prior,3,5,9,8.0,33120,Organic Egg Whites,86,eggs,16,dairy eggs,1,1
1,2,202279,prior,3,5,9,8.0,28985,Michigan Organic Kale,83,fresh vegetables,4,produce,2,1
2,2,202279,prior,3,5,9,8.0,9327,Garlic Powder,104,spices seasonings,13,pantry,3,0
3,2,202279,prior,3,5,9,8.0,45918,Coconut Butter,19,oils vinegars,13,pantry,4,1
4,2,202279,prior,3,5,9,8.0,30035,Natural Sweetener,17,baking ingredients,13,pantry,5,0

--- Table Schema Information ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32434489 entries, 0 to 32434488
Data columns (total 15 columns):
 #   Column                  Dtype
---  ------                  -----
 0   order_id                int32
 1   user_id                 int32
 2   eval_set                category
 3   order_number            int8
 4   order_dow               int8
 5   order_hour_of_day       int8
 6   days_since_prior_order  float32
 7   product_id              int32
 8   product_name            category
 9   aisle_id                int16
 10  aisle                   category
 11  department_id           int8
 12  department              category
 13  add_to_cart_order       int16
 14  reordered               int8
dtypes: category(4), float32(1), int16(2), int32(3), int8(5)
memory usage: 1022.1 MB

Table Dimensions: (32434489, 15)

In [34]:
# Check for redundant columns caused by merging (typically identified by '_x' or '_y' suffixes)
duplicate_cols = [col for col in prior_final.columns if '_x' in col or '_y' in col]

print(f"Duplicate columns found: {duplicate_cols}")

Duplicate columns found: []

In [17]:
# --- SETTINGS ---
PUSH_URL = f"https://{GIT_USERNAME}:{GIT_TOKEN}@github.com/{REPO_OWNER}/{GIT_REPO}.git"

# --- 1. PREPARE ---
!git config --global user.email "{GIT_EMAIL}"
!git config --global user.name "{GIT_USERNAME}"
# !git pull {PUSH_URL} main  # Uncomment if working with others

# --- 2. SYNC FROM DRIVE ---
!cp "{SOURCE_PATH}" ./notebooks/

# --- 3. PUSH TO GITHUB ---
!git add .
!git commit -m "Step 1: Updated data cleaning logic and downcasting" || echo "No changes to commit"
!git push {PUSH_URL} main

print(f"✅ Successfully updated: https://github.com/{REPO_OWNER}/{GIT_REPO}")

[main fc43b26] Step 1: Updated data cleaning logic and downcasting
 1 file changed, 1 insertion(+), 1 deletion(-)
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 2 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 851 bytes | 851.00 KiB/s, done.
Total 4 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To https://github.com/nhnminh1409/instacart-market-basket-analysis.git
   d19a171..fc43b26  main -> main
✅ Successfully updated: https://github.com/nhnminh1409/instacart-market-basket-analysis